import React, { useState, useRef } from 'react';
import { ArrowRight, Github, ExternalLink, Play, Palette, Download, Sparkles } from 'lucide-react';
import Footer from '../components/Footer';

const CurveLabLanding = () => {
  const [hoveredCard, setHoveredCard] = useState<string | null>(null);
  const curvesSectionRef = useRef<HTMLDivElement>(null);

  const scrollToCurves = () => {
    if (curvesSectionRef.current) {
      const yOffset = 110; 
      const y = curvesSectionRef.current.getBoundingClientRect().top + window.pageYOffset + yOffset;
      window.scrollTo({ top: y, behavior: 'smooth' });
    }
  };

  const curves = [
    {
        id: "hypocycloid",
        name: "Hypocycloid",
        description:
        "Elegant curves formed by circles rolling inside other circles, creating star-like patterns with mathematical precision.",
        preview: (
            <svg viewBox="0 0 120 120" className="w-full h-full" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M 60,20 
                    C 80,20 100,40 100,60 
                    C 100,80 80,100 60,100 
                    C 40,100 20,80 20,60 
                    C 20,40 40,20 60,20 Z"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    opacity="0.85"
                />
                <circle cx="60" cy="60" r="2.5" fill="currentColor" opacity="0.6" />
                <circle cx="85" cy="35" r="1.5" fill="#00E5FF" opacity="0.8" />
            </svg>
        ),
    },
    {
        id: "epicycloid",
        name: "Epicycloid",
        description:
        "Graceful spirals generated by circles rolling around the outside of fixed circles, producing flowing organic forms.",
        preview: (
        <svg viewBox="0 0 120 120" className="w-full h-full">
            <path
            d="M 60,15 Q 105,30 95,75 Q 60,105 25,75 Q 15,30 60,15"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            opacity="0.8"
            />
            <path
            d="M 60,25 Q 95,40 85,75 Q 60,95 35,75 Q 25,40 60,25"
            fill="none"
            stroke="currentColor"
            strokeWidth="1"
            opacity="0.4"
            />
            <circle cx="35" cy="85" r="1.5" fill="#FF4081" opacity="0.8" />
        </svg>
        ),
    },
    {
        id: "epitrochoid",
        name: "Epitrochoid",
        description:
        "Intricate curves formed by tracing a point attached to a circle rolling around the outside of another circle.",
        preview: (
        <svg viewBox="0 0 120 120" className="w-full h-full">
            <circle
            cx="60"
            cy="60"
            r="40"
            fill="none"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0.3"
            />
            <circle
            cx="60"
            cy="60"
            r="25"
            fill="none"
            stroke="currentColor"
            strokeWidth="0.8"
            opacity="0.5"
            />
            <circle
            cx="60"
            cy="60"
            r="12"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.2"
            opacity="0.7"
            />
            <circle cx="60" cy="60" r="3" fill="currentColor" opacity="0.8" />
            <circle cx="95" cy="60" r="1.5" fill="#76FF03" opacity="0.8" />
        </svg>
        ),
    },
    {
        id: "hypotrochoid",
        name: "Hypotrochoid",
        description:
        "Curves traced by a point attached to a circle rolling inside another circle, creating complex loops.",
        preview: (
        <svg viewBox="0 0 120 120" className="w-full h-full">
            <path
            d="M 15,60 Q 35,25 60,60 Q 85,95 105,60"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            opacity="0.8"
            />
            <path
            d="M 60,15 Q 25,35 60,60 Q 95,85 60,105"
            fill="none"
            stroke="currentColor"
            strokeWidth="1"
            opacity="0.4"
            />
            <circle cx="60" cy="60" r="2" fill="currentColor" opacity="0.6" />
            <circle cx="25" cy="35" r="1.5" fill="#7C4DFF" opacity="0.8" />
        </svg>
        ),
    },
    {
        id: "lissajous",
        name: "Lissajous",
        description:
        "Harmonious patterns created by the intersection of perpendicular oscillations, revealing mathematical beauty in motion.",
        preview: (
        <svg viewBox="0 0 120 120" className="w-full h-full">
            <path
            d="M 20,60 Q 40,20 60,60 Q 80,100 100,60"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            opacity="0.8"
            />
            <path
            d="M 60,20 Q 100,40 60,60 Q 20,80 60,100"
            fill="none"
            stroke="currentColor"
            strokeWidth="1"
            opacity="0.4"
            />
            <circle cx="100" cy="80" r="1.5" fill="#00E5FF" opacity="0.8" />
        </svg>
        ),
    },
    {
        id: "rose",
        name: "Rose",
        description:
        "Symmetrical petal-like patterns that emerge from polar equations, combining natural beauty with geometric precision.",
        preview: (
        <svg viewBox="0 0 120 120" className="w-full h-full">
            <path
            d="M 60,20 Q 100,40 80,80 Q 60,100 40,80 Q 20,60 40,40 Q 60,20 80,40 Q 100,60 80,80"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            opacity="0.8"
            />
            <circle cx="60" cy="60" r="1.5" fill="currentColor" opacity="0.6" />
            <circle cx="80" cy="40" r="1.5" fill="#FF4081" opacity="0.8" />
        </svg>
        ),
    },
];

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-yellow-50 to-orange-100 text-gray-700" 
         style={{ fontFamily: 'Space Grotesk, system-ui, -apple-system, sans-serif' }}>
      <div className="fixed inset-0 opacity-20">
        <div className="absolute inset-0 bg-gradient-to-br from-orange-100 via-yellow-50 to-orange-200" />
        <div className="absolute top-20 left-20 w-2 h-2 bg-cyan-400 rounded-full animate-pulse" />
        <div className="absolute top-40 right-32 w-1.5 h-1.5 bg-pink-400 rounded-full animate-pulse" style={{ animationDelay: '1s' }} />
        <div className="absolute bottom-32 left-1/3 w-2 h-2 bg-lime-400 rounded-full animate-pulse" style={{ animationDelay: '2s' }} />
      </div>
      <div className="relative z-10">
        <header className="px-6 py-16 md:py-24">
          <div className="max-w-6xl mx-auto text-center">
            <h1 className="text-6xl md:text-8xl font-black mb-8 tracking-wide text-gray-800">
              <span className="text-orange-500">Curve</span><span className="text-gray-700">Lab</span>
            </h1>
            <p className="text-xl md:text-2xl text-gray-600 mb-12 font-bold max-w-2xl mx-auto leading-relaxed">
              Play with the magic of mathematical curves
            </p>
            <button 
              onClick={scrollToCurves}
              className="inline-flex items-center gap-4 px-12 py-6 bg-orange-500 text-white rounded-full hover:bg-orange-600 transition-all duration-300 hover:scale-110 hover:-translate-y-1 active:scale-95 font-black text-xl shadow-xl hover:shadow-2xl transform hover:rotate-1"
            >
              <Sparkles className="w-6 h-6 text-cyan-300" />
              Start Creating
              <ArrowRight className="w-6 h-6" />
            </button>
          </div>
        </header>

        <main className="px-6 pb-20">
            <div className="max-w-7xl mx-auto">
                <div ref={curvesSectionRef} className="text-center mb-20">
                <h2 className="text-4xl md:text-5xl font-black mb-6 tracking-wide text-gray-800">
                    Mathematical Playgrounds
                </h2>
                <p className="text-xl text-gray-600 max-w-2xl mx-auto font-bold">
                    Each curve is a creative adventure waiting to be explored
                </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
                    {curves.map((curve) => (
                        <div key={curve.id} className="relative">
                        <a
                            href={`/${curve.id}`}
                            className="group relative block w-full h-80 bg-gradient-to-br from-orange-50 to-yellow-50 backdrop-blur-sm rounded-3xl p-8 border-3 border-orange-300 transition-all duration-500 overflow-hidden hover:scale-105 hover:rotate-1 shadow-xl hover:shadow-2xl"
                            onMouseEnter={() => setHoveredCard(curve.id)}
                            onMouseLeave={() => setHoveredCard(null)}
                        >
                            <div
                            className={`absolute inset-0 bg-gradient-to-br from-orange-400 to-orange-500 transition-all duration-500 ease-out ${
                                hoveredCard === curve.id
                                ? 'translate-y-0 opacity-100'
                                : 'translate-y-full opacity-0'
                            }`}
                            />
                            <div
                            className={`absolute inset-0 transition-all duration-500 ease-out ${
                                hoveredCard === curve.id
                                ? 'opacity-100'
                                : 'opacity-0'
                            }`}
                            style={{
                                background: `radial-gradient(circle at 20% 80%, #00E5FF33 0%, transparent 50%),
                                            radial-gradient(circle at 80% 20%, #FF408133 0%, transparent 50%),
                                            radial-gradient(circle at 40% 40%, #76FF0333 0%, transparent 50%)`
                            }}
                            />
                            <div className="relative z-10 h-full flex flex-col items-center justify-center">
                            <div
                                className={`w-24 h-24 mb-6 transition-all duration-500 ${
                                hoveredCard === curve.id ? 'translate-y-[-20px] scale-110' : ''
                                } ${
                                hoveredCard === curve.id
                                    ? 'text-white'
                                    : 'text-orange-500 group-hover:text-orange-600'
                                }`}
                            >
                                {curve.preview}
                            </div>
                            <h3
                                className={`text-xl font-black transition-all duration-500 ${
                                hoveredCard === curve.id ? 'opacity-0 h-0' : 'opacity-100 h-auto text-gray-800'
                                }`}
                            >
                                {curve.name}
                            </h3>
                            <div
                                className={`w-full transition-all duration-500 text-center ${
                                hoveredCard === curve.id
                                    ? 'max-h-32 opacity-100 mt-4'
                                    : 'max-h-0 opacity-0'
                                }`}
                            >
                                <p
                                className={`text-sm leading-relaxed font-bold ${
                                    hoveredCard === curve.id
                                    ? 'text-white'
                                    : 'text-gray-600'
                                }`}
                                >
                                {curve.description}
                                </p>
                            </div>
                            </div>
                        </a>
                        </div>
                    ))}
                </div>

                <div className="mt-32 text-center">
                <div className="max-w-5xl mx-auto">
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-16">
                    <div className="space-y-6">
                        <div className="w-20 h-20 mx-auto bg-gradient-to-br from-cyan-400 to-cyan-500 rounded-3xl flex items-center justify-center shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-105 hover:rotate-3">
                        <Play className="w-10 h-10 text-white" />
                        </div>
                        <h4 className="text-2xl font-black text-gray-800">Real-time Magic</h4>
                        <p className="text-base text-gray-600 font-bold">
                        Watch curves dance as you play with parameters and discover endless possibilities
                        </p>
                    </div>
                    <div className="space-y-6">
                        <div className="w-20 h-20 mx-auto bg-gradient-to-br from-pink-400 to-pink-500 rounded-3xl flex items-center justify-center shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-105 hover:rotate-3">
                        <Palette className="w-10 h-10 text-white" />
                        </div>
                        <h4 className="text-2xl font-black text-gray-800">Creative Control</h4>
                        <p className="text-base text-gray-600 font-bold">
                        Fine-tune every detail with intuitive controls and mathematical precision
                        </p>
                    </div>
                    <div className="space-y-6">
                        <div className="w-20 h-20 mx-auto bg-gradient-to-br from-lime-400 to-lime-500 rounded-3xl flex items-center justify-center shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-105 hover:rotate-3">
                        <Download className="w-10 h-10 text-white" />
                        </div>
                        <h4 className="text-2xl font-black text-gray-800">Export & Share</h4>
                        <p className="text-base text-gray-600 font-bold">
                        Save your creations as high-quality SVG files to use anywhere
                        </p>
                    </div>
                    </div>
                </div>
                </div>

                <div className="mt-32 text-center">
                    <div className="max-w-3xl mx-auto bg-gradient-to-br from-orange-50 to-yellow-50 backdrop-blur-sm rounded-3xl p-16 border-3 border-orange-300 shadow-2xl relative overflow-hidden">
                        <div className="absolute top-6 right-6 w-3 h-3 bg-cyan-400 rounded-full animate-pulse" />
                        <div className="absolute bottom-6 left-6 w-2 h-2 bg-pink-400 rounded-full animate-pulse" style={{ animationDelay: '1s' }} />
                        <div className="absolute top-1/2 left-8 w-2 h-2 bg-lime-400 rounded-full animate-pulse" style={{ animationDelay: '2s' }} />
                        <h3 className="text-3xl font-black mb-6 tracking-wide text-gray-800">
                            Ready to Explore?
                        </h3>
                        <p className="text-gray-600 mb-10 font-bold text-lg">
                            Pick any curve above to start your creative journey and imagine something amazing.
                        </p>
                        <p className="text-sm text-gray-500 flex items-center justify-center flex-wrap">
                            Developers can{" "}
                            <a
                                href="https://github.com/..."
                                className="inline-flex items-center gap-2 ml-2 align-middle leading-none hover:text-orange-500 transition font-black"
                            >
                                <Github className="w-5 h-5" />
                                <span className="leading-none">explore the code on GitHub</span>
                            </a>
                            .
                        </p>
                    </div>
                </div>
            </div>
        </main>
        
        <Footer />
      </div>
    </div>
  );
};

export default CurveLabLanding;