import React, { useState, useRef } from 'react';
import { ArrowRight, Github, ExternalLink, Play, Palette, Download } from 'lucide-react';
import Footer from '../components/Footer';
import { Helmet } from 'react-helmet';

const CurveLabLanding = () => {
  const [hoveredCard, setHoveredCard] = useState<string | null>(null);
  const curvesSectionRef = useRef<HTMLDivElement>(null);

  const scrollToCurves = () => {
    if (curvesSectionRef.current) {
      const yOffset = 145; 
      const y = curvesSectionRef.current.getBoundingClientRect().top + window.pageYOffset + yOffset;
      window.scrollTo({ top: y, behavior: 'smooth' });
    }
  };

  const curves = [
    {
        id: "hypocycloid",
        name: "Hypocycloid",
        description:
        "Elegant curves formed by circles rolling inside other circles, creating star-like patterns with mathematical precision.",
        preview: (
            <svg viewBox="0 0 120 120" className="w-full h-full" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M 60,20 
                    C 80,20 100,40 100,60 
                    C 100,80 80,100 60,100 
                    C 40,100 20,80 20,60 
                    C 20,40 40,20 60,20 Z"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    opacity="0.85"
                />
                <circle cx="60" cy="60" r="2.5" fill="currentColor" opacity="0.6" />
            </svg>
        ),
    },
    {
        id: "epicycloid",
        name: "Epicycloid",
        description:
        "Graceful spirals generated by circles rolling around the outside of fixed circles, producing flowing organic forms.",
        preview: (
        <svg viewBox="0 0 120 120" className="w-full h-full">
            <path
            d="M 60,15 Q 105,30 95,75 Q 60,105 25,75 Q 15,30 60,15"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            opacity="0.8"
            />
            <path
            d="M 60,25 Q 95,40 85,75 Q 60,95 35,75 Q 25,40 60,25"
            fill="none"
            stroke="currentColor"
            strokeWidth="1"
            opacity="0.4"
            />
        </svg>
        ),
    },
    {
        id: "epitrochoid",
        name: "Epitrochoid",
        description:
        "Intricate curves formed by tracing a point attached to a circle rolling around the outside of another circle.",
        preview: (
        <svg viewBox="0 0 120 120" className="w-full h-full">
            <circle
            cx="60"
            cy="60"
            r="40"
            fill="none"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0.3"
            />
            <circle
            cx="60"
            cy="60"
            r="25"
            fill="none"
            stroke="currentColor"
            strokeWidth="0.8"
            opacity="0.5"
            />
            <circle
            cx="60"
            cy="60"
            r="12"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.2"
            opacity="0.7"
            />
            <circle cx="60" cy="60" r="3" fill="currentColor" opacity="0.8" />
        </svg>
        ),
    },
    {
        id: "hypotrochoid",
        name: "Hypotrochoid",
        description:
        "Curves traced by a point attached to a circle rolling inside another circle, creating complex loops.",
        preview: (
        <svg viewBox="0 0 120 120" className="w-full h-full">
            <path
            d="M 15,60 Q 35,25 60,60 Q 85,95 105,60"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            opacity="0.8"
            />
            <path
            d="M 60,15 Q 25,35 60,60 Q 95,85 60,105"
            fill="none"
            stroke="currentColor"
            strokeWidth="1"
            opacity="0.4"
            />
            <circle cx="60" cy="60" r="2" fill="currentColor" opacity="0.6" />
        </svg>
        ),
    },
    {
        id: "lissajous",
        name: "Lissajous",
        description:
        "Harmonious patterns created by the intersection of perpendicular oscillations, revealing mathematical beauty in motion.",
        preview: (
        <svg viewBox="0 0 120 120" className="w-full h-full">
            <path
            d="M 20,60 Q 40,20 60,60 Q 80,100 100,60"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            opacity="0.8"
            />
            <path
            d="M 60,20 Q 100,40 60,60 Q 20,80 60,100"
            fill="none"
            stroke="currentColor"
            strokeWidth="1"
            opacity="0.4"
            />
        </svg>
        ),
    },
    {
        id: "rose",
        name: "Rose",
        description:
        "Symmetrical petal-like patterns that emerge from polar equations, combining natural beauty with geometric precision.",
        preview: (
        <svg viewBox="0 0 120 120" className="w-full h-full">
            <path
            d="M 60,20 Q 100,40 80,80 Q 60,100 40,80 Q 20,60 40,40 Q 60,20 80,40 Q 100,60 80,80"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            opacity="0.8"
            />
            <circle cx="60" cy="60" r="1.5" fill="currentColor" opacity="0.6" />
        </svg>
        ),
    },
];


  return (
    <div className="min-h-screen bg-black text-white">
      <Helmet>
        <title>Curve Lab</title>
      </Helmet>  
      <div className="fixed inset-0 opacity-5">
        <div className="absolute inset-0 bg-gradient-to-br from-gray-900 via-black to-gray-900" />
      </div>
      <div className="relative z-10">
        <header className="px-6 py-16 md:py-24">
          <div className="max-w-6xl mx-auto text-center">
            <h1 className="text-5xl md:text-7xl font-light mb-6 tracking-tight">
              <span className="font-extralight">Curve</span><span className="font-normal">Lab</span>
            </h1>
            <p className="text-xl md:text-2xl text-gray-400 mb-12 font-light max-w-2xl mx-auto leading-relaxed">
              Explore the art of mathematical curves
            </p>
            <button 
              onClick={scrollToCurves}
              className="inline-flex items-center gap-3 px-8 py-4 bg-white text-black rounded-full hover:bg-gray-100 transition-all duration-300 hover:scale-105 font-medium"
            >
              Start Designing
              <ArrowRight className="w-5 h-5" />
            </button>
          </div>
        </header>

        <main className="px-6 pb-20">
            <div className="max-w-7xl mx-auto">
                <div ref={curvesSectionRef} className="text-center mb-16">
                <h2 className="text-3xl md:text-4xl font-light mb-4 tracking-tight">
                    Mathematical Artistry
                </h2>
                <p className="text-lg text-gray-400 max-w-2xl mx-auto font-light">
                    Each curve tells a story of mathematical beauty, waiting to be discovered and customized
                </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {curves.map((curve) => (
                        <div key={curve.id} className="relative">
                        <a
                            href={`/${curve.id}`}
                            className="group relative block w-full h-80 bg-white/[0.02] backdrop-blur-sm rounded-2xl p-6 border border-white/[0.08] transition-all duration-500 overflow-hidden hover:scale-[1.02]"
                            onMouseEnter={() => setHoveredCard(curve.id)}
                            onMouseLeave={() => setHoveredCard(null)}
                        >
                            <div
                            className={`absolute inset-0 bg-gradient-to-t from-gray-300 to-gray-200 transition-all duration-300 ease-in-out ${
                                hoveredCard === curve.id
                                ? 'translate-y-0 opacity-100'
                                : 'translate-y-full opacity-0'
                            }`}
                            />
                            <div className="relative z-10 h-full flex flex-col items-center justify-center">
                            <div
                                className={`w-16 h-16 mb-4 transition-all duration-300 ${
                                hoveredCard === curve.id ? 'translate-y-[-20px]' : ''
                                } ${
                                hoveredCard === curve.id
                                    ? 'text-black'
                                    : 'text-gray-300 group-hover:text-white'
                                }`}
                            >
                                {curve.preview}
                            </div>
                            <h3
                                className={`text-lg font-medium transition-all duration-300 ${
                                hoveredCard === curve.id ? 'opacity-0 h-0' : 'opacity-100 h-auto'
                                }`}
                            >
                                {curve.name}
                            </h3>
                            <div
                                className={`w-full transition-all duration-300 text-center ${
                                hoveredCard === curve.id
                                    ? 'max-h-32 opacity-100 mt-4'
                                    : 'max-h-0 opacity-0'
                                }`}
                            >
                                <p
                                className={`text-sm leading-relaxed font-light ${
                                    hoveredCard === curve.id
                                    ? 'text-gray-800'
                                    : 'text-gray-400'
                                }`}
                                >
                                {curve.description}
                                </p>
                            </div>
                            </div>
                            <div className="absolute inset-0 rounded-2xl bg-gradient-to-br from-white/[0.02] to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none" />
                        </a>
                        </div>
                    ))}
                </div>


                <div className="mt-24 text-center">
                <div className="max-w-4xl mx-auto">
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
                    <div className="space-y-4">
                        <div className="w-12 h-12 mx-auto bg-white/[0.05] rounded-xl flex items-center justify-center">
                        <Play className="w-6 h-6 text-gray-300" />
                        </div>
                        <h4 className="text-lg font-medium">Real-time Visualization</h4>
                        <p className="text-sm text-gray-400 font-light">
                        Watch curves evolve as you adjust parameters with smooth, responsive animations
                        </p>
                    </div>
                    <div className="space-y-4">
                        <div className="w-12 h-12 mx-auto bg-white/[0.05] rounded-xl flex items-center justify-center">
                        <Palette className="w-6 h-6 text-gray-300" />
                        </div>
                        <h4 className="text-lg font-medium">Precise Control</h4>
                        <p className="text-sm text-gray-400 font-light">
                        Fine-tune every aspect with intuitive controls and mathematical precision
                        </p>
                    </div>
                    <div className="space-y-4">
                        <div className="w-12 h-12 mx-auto bg-white/[0.05] rounded-xl flex items-center justify-center">
                        <Download className="w-6 h-6 text-gray-300" />
                        </div>
                        <h4 className="text-lg font-medium">Export Quality</h4>
                        <p className="text-sm text-gray-400 font-light">
                        Export your creations as high-resolution SVG files for any application
                        </p>
                    </div>
                    </div>
                </div>
                </div>

                <div className="mt-24 text-center">
                    <div className="max-w-2xl mx-auto bg-white/[0.02] backdrop-blur-sm rounded-2xl p-12 border border-white/[0.08]">
                        <h3 className="text-2xl font-light mb-4 tracking-tight">
                            Explore CurveLab
                        </h3>
                        <p className="text-gray-400 mb-8 font-light">
                            Select any curve above to discover and customize its unique patterns.
                        </p>
                        <p className="text-sm text-gray-500 flex items-center justify-center flex-wrap">
                            Developers can{" "}
                            <a
                                href="https://github.com/U1000000000000/CurveLab"
                                className="inline-flex items-center gap-1 ml-1 align-middle leading-none hover:text-white transition"
                            >
                                <Github className="w-4 h-4" />
                                <span className="leading-none">view the source on GitHub</span>
                            </a>
                            .
                        </p>
                    </div>
                </div>
            </div>
        </main>
        
        <Footer />
      </div>
    </div>
  );
};

export default CurveLabLanding;
